language: ruby

services:
  - docker

script:
  - docker pull kaashif1/cyclotomic:latest
  - docker run --rm -it -v $(pwd):/cyclotomic kaashif1/cyclotomic:latest /bin/sh -c "cd /cyclotomic && cargo +nightly test --release && cargo +nightly build --release"
