language: rust

rust:
  - stable
  - beta
  - nightly

# nightly failures don't cause overall failure
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

# cache dependencies for faster build
cache: cargo

# need to specify script for documentation build
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose --no-deps --document-private-items
  # Create an index.html in the generated documentation folder
  - echo '<!DOCTYPE html><html lang="en"><meta http-equiv=refresh content=0;url=cyclotomic/index.html></html>' > target/doc/index.html

# deploy documentation to github pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  verbose: true
  local_dir: target/doc
  on:
    branch: master
