language: rust

rust:
  - stable
  - beta
  - nightly

# nightly failures don't cause overall failure
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

# cache dependencies for faster build
cache: cargo

# need to specify script for documentation build
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose --no-deps --document-private-items

# deploy documentation to github pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  allow_empty_commit: true
  verbose: true
  local_dir: target/doc
  on:
    branch: master
