language: rust

# only nightly due to use of #[feature(test)]
rust:
  - nightly

jobs:
  fast_finish: true

# cache dependencies for faster build
cache: cargo

# need to specify script for documentation build
script:
  - ./ci-build.sh
  - cargo build --verbose --release
  - cargo test --verbose --release
  - cargo doc --verbose --no-deps --document-private-items
  - echo '<!DOCTYPE html><html lang="en"><meta http-equiv=refresh content=0;url=cyclotomic/index.html></html>' > target/doc/index.html

# deploy documentation to github pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  verbose: true
  local_dir: target/doc
  on:
    branch: master
