[package]
name = "cyclotomic"
version = "0.1.0"
authors = ["romo <robmoore121@gmail.com>", "Kaashif Hymabaccus <kaashif@kaashif.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2.1"
combinations = "0.1.0"
quickcheck = "0.9.2"
rand = "0.7.3"
divisors = "0.2.1"
rand_chacha = "0.2.2"
rustc-hash = "1.1.0"

[[bin]]
name = "arithmetic-benchmark"

[[bin]]
name = "inversion-benchmark"

[profile.release]
debug = true

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "docs/katex-header.html" ]
